import { NextResponse } from "next/server";
import { query, transaction } from "@/lib/olv/db";
import { createSession, OLV_COOKIE } from "@/lib/olv/session";
import { verifyPassword } from "@/lib/olv/security";
import { email } from "@/lib/olv/validation";
import { guardLeadRequest } from "@/lib/request-guard";
import { audit } from "@/lib/olv/audit";

export async function POST(request:Request){const limited=guardLeadRequest(request,"olv-login",10);if(limited)return limited;const origin=request.headers.get("origin");if(origin&&origin!==new URL(request.url).origin)return Response.json({error:"Invalid request."},{status:403});let body:unknown;try{body=await request.json();}catch{return Response.json({error:"Invalid request."},{status:400});}const data=body as {email?:string;password?:string};const parsed=email.safeParse(data.email);if(!parsed.success||typeof data.password!=="string")return Response.json({error:"Email or password is incorrect."},{status:401});const {rows}=await query<{id:string;recovery_email:string;password_hash:string|null;organization_id:string}>(`SELECT u.id,u.recovery_email,u.password_hash,om.organization_id FROM users u JOIN organization_members om ON om.user_id=u.id WHERE u.recovery_email=$1 AND u.activated_at IS NOT NULL LIMIT 1`,[parsed.data]);const user=rows[0];if(!user?.password_hash||!(await verifyPassword(user.password_hash,data.password)))return Response.json({error:"Email or password is incorrect."},{status:401});const session=await createSession(user.id,user.organization_id,request);await transaction(async c=>audit(c,{organizationId:user.organization_id,userId:user.id},"LOGIN","session"));const response=NextResponse.json({ok:true});response.cookies.set(OLV_COOKIE,session.token,{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",path:"/",maxAge:session.maxAge});return response;}
