import sanitizeHtml from "sanitize-html";
import nodemailer from "nodemailer";
import PostalMime from "postal-mime";
import { randomUUID } from "node:crypto";
import { normalizeSubject } from "./validation";

export function cleanHtml(value:string){return sanitizeHtml(value,{allowedTags:["p","br","div","span","strong","b","em","i","u","blockquote","ul","ol","li","a","pre","code","table","tbody","tr","td","th"],allowedAttributes:{a:["href","title"],td:["colspan","rowspan"],th:["colspan","rowspan"]},allowedSchemes:["http","https","mailto"],disallowedTagsMode:"discard",transformTags:{a:(_tag,attrs)=>({tagName:"a",attribs:{...attrs,rel:"noopener noreferrer",target:"_blank"}})}});}
export async function parseMime(raw:Uint8Array){const parsed=await new PostalMime().parse(raw);return {messageId:parsed.messageId||`<${randomUUID()}@olv.invalid>`,subject:parsed.subject||"(no subject)",text:parsed.text||"",html:parsed.html?cleanHtml(parsed.html):null,inReplyTo:parsed.inReplyTo||null,references:parsed.references?parsed.references.split(/\s+/).filter(Boolean):[],from:parsed.from,to:parsed.to||[],cc:parsed.cc||[],replyTo:parsed.replyTo,attachments:parsed.attachments||[],date:parsed.date?new Date(parsed.date):new Date()};}
export async function buildMime(input:{from:string;to:string[];cc?:string[];bcc?:string[];subject:string;text:string;html?:string;messageId:string;inReplyTo?:string|null;references?:string[];attachments?:{filename:string;contentType:string;content:Uint8Array}[]}){const transport=nodemailer.createTransport({streamTransport:true,buffer:true,newline:"unix"});const result=await transport.sendMail({from:input.from,to:input.to,cc:input.cc,bcc:input.bcc,subject:input.subject,text:input.text,html:input.html?cleanHtml(input.html):undefined,messageId:input.messageId,inReplyTo:input.inReplyTo||undefined,references:input.references,date:new Date(),attachments:input.attachments?.map(a=>({filename:a.filename,contentType:a.contentType,content:Buffer.from(a.content)}))});return new Uint8Array(result.message as Buffer);}
export function chooseThread(headers:{inReplyTo?:string|null;references?:string[]},messages:{id:string;thread_id:string;internet_message_id:string}[]){const candidates=[headers.inReplyTo,...(headers.references||[]).reverse()].filter(Boolean);for(const id of candidates){const found=messages.find(m=>m.internet_message_id===id);if(found)return found.thread_id;}return null;}
export async function sendSystemEmail(to:string,subject:string,text:string){const from=process.env.INVITATION_FROM_EMAIL;if(!from)throw new Error("INVITATION_FROM_EMAIL is required.");const {SesMailProvider}=await import("./aws");const raw=await buildMime({from,to:[to],subject,text,messageId:`<${randomUUID()}@${from.split("@")[1]}>`});return new SesMailProvider().sendRaw(raw);}
export {normalizeSubject};
