import type { Metadata } from "next";
import { BusinessPage } from "@/components/business-shell";
import { InquiryForm } from "@/components/inquiry-form";

export const metadata: Metadata = { title: "Partnerships", description: "Partner with RoleField to deliver multilingual autonomous customer operations across the GCC.", alternates: { canonical: "/partnerships" } };

export default function PartnershipsPage() {
  return <BusinessPage><section className="business-hero"><p className="eyebrow"><i /> PARTNERSHIPS</p><h1>Build the customer operations ecosystem with us.</h1><p>We partner with technology providers, implementation specialists and trusted advisers who understand how GCC businesses serve their customers.</p></section><section className="business-section partnership-types"><header><p className="eyebrow"><i /> PARTNER MODELS</p><h2>Different strengths.<br />One complete outcome.</h2></header><div className="value-grid"><article><span>01</span><h3>Technology partners</h3><p>Connect CRM, contact-centre, telephony, calendar, payments and business systems into complete workflows.</p></article><article><span>02</span><h3>Delivery partners</h3><p>Design, implement and optimise customer operations for organisations in your industry or market.</p></article><article><span>03</span><h3>Channel partners</h3><p>Bring RoleField to customers who need regional, multilingual automation with accountable local support.</p></article></div></section><section className="business-section partner-principles"><div><p className="eyebrow"><i /> WHAT MATTERS</p><h2>A partnership built around customer trust.</h2></div><ul><li><b>Clear ownership</b><span>Defined responsibilities from opportunity through implementation and support.</span></li><li><b>Shared standards</b><span>Security, privacy and quality expectations agreed before customer delivery.</span></li><li><b>Measurable value</b><span>Success tied to operational outcomes, customer experience and sustainable adoption.</span></li></ul></section><section className="business-section partnership-form-section"><div><p className="eyebrow"><i /> BECOME A PARTNER</p><h2>Start the conversation.</h2><p>Share your expertise, market and the customers you serve. We will respond within one business day.</p></div><div className="form-panel"><InquiryForm kind="partnership" /></div></section></BusinessPage>;
}
